# add new mc requests here like in the example sample shown

example:
  requestID: "HIG-RunIISummer16NanoAODv5-00031" # the string of the McM request
  label: "GluGluH_NanoAOD" # label used for personal bookkeeping
  inputFiles: "" # specified input files, either path to a filelist or a dbs entry
  workdir: "workdir_nano" # path to the desired workdir
  outputPath: "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/sbrommer/gc_storage/private_mc_16" # path to the desired output location. This path should be given in correct grid control syntax
  batchSystem: "freiburg" # batch system option: currently available: freiburg
  totalEvents: 100000 # total number of events in the task. If an input file is speficied, the whole file will be processed instead
  eventsPerJob: 1000 # number of events per job

ttbar_lhegen:
  requestID: "TOP-RunIISummer20UL18wmLHEGEN-00002"
  label: "ttbar_ul18_summer20"
  inputFiles: ""
  workdir: "ttbar_lhegen"
  outputPath: "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/sbrommer/gc_storage/private_ul/ttbar"
  batchSystem: "freiburg"
  totalEvents: 400000
  eventsPerJob: 1000
ttbar_sim:
  requestID: "TOP-RunIISummer20UL18SIM-00002"
  label: "ttbar_ul18_summer20"
  inputFiles: "/work/sbrommer/mc_production/ul/LocalMonteCarloProduction/ttbar_lhegen/filelist.txt"
  workdir: "ttbar_sim"
  outputPath: "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/sbrommer/gc_storage/private_ul/ttbar"
  batchSystem: "freiburg"
  totalEvents: 400000
  eventsPerJob: 100
ttbar_premix:
  requestID: "TOP-RunIISummer20UL18DIGIPremix-00002"
  label: "ttbar_premix_ul18_summer20"
  inputFiles: "/work/sbrommer/mc_production/ul/LocalMonteCarloProduction/ttbar_sim/filelist.txt"
  workdir: "ttbar_premix"
  outputPath: "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/sbrommer/gc_storage/private_ul/ttbar"
  batchSystem: "freiburg"
  totalEvents: 400000
  eventsPerJob: 100
ttbar_hlt:
  requestID: "TOP-RunIISummer20UL18HLT-00002"
  label: "ttbar_hlt_ul18_summer20"
  inputFiles: "/work/sbrommer/mc_production/ul/LocalMonteCarloProduction/ttbar_premix/filelist.txt"
  workdir: "ttbar_hlt"
  outputPath: "srm://cmssrm-kit.gridka.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/cms/disk-only/store/user/sbrommer/gc_storage/private_ul/ttbar"
  batchSystem: "freiburg"
  totalEvents: 400000
  eventsPerJob: 3000
